packages:
  - '.'

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  electron: true
  esbuild: true
  vue-demi: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - electron
  - esbuild
  - vue-demi
