import { contextBridge, ipcRenderer } from 'electron';
import type { VtStudioApi } from '@shared/contracts/preload';

const api: VtStudioApi = {
  app: {
    getInfo: () => ipcRenderer.invoke('app:get-info'),
    reportRendererError: (payload) => ipcRenderer.invoke('app:renderer-error', payload),
  },
  shell: {
    listExternalLinks: () => ipcRenderer.invoke('shell:list-external-links'),
    openExternalByKey: (payload) => ipcRenderer.invoke('shell:open-external-by-key', payload),
  },
  window: {
    getState: () => ipcRenderer.invoke('window:get-state'),
    minimize: () => ipcRenderer.invoke('window:minimize'),
    toggleMaximize: () => ipcRenderer.invoke('window:toggle-maximize'),
    close: () => ipcRenderer.invoke('window:close'),
  },
  agent: {
    getSocketInfo: () => ipcRenderer.invoke('agent:get-socket-info'),
    script: {
      getMemoryHistory: (payload) => ipcRenderer.invoke('agent:script:get-memory-history', payload),
      clearMemory: (payload) => ipcRenderer.invoke('agent:script:clear-memory', payload),
      checkSourceEvents: (payload) => ipcRenderer.invoke('agent:script:check-source-events', payload),
      getModelCapability: () => ipcRenderer.invoke('agent:script:get-model-capability'),
      getWorkspace: (payload) => ipcRenderer.invoke('agent:script:get-workspace', payload),
      updateWorkspaceField: (payload) => ipcRenderer.invoke('agent:script:update-workspace-field', payload),
      upsertScript: (payload) => ipcRenderer.invoke('agent:script:upsert-script', payload),
      deleteScript: (payload) => ipcRenderer.invoke('agent:script:delete-script', payload),
    },
  },
  media: {
    createUrl: (payload) => ipcRenderer.invoke('media:create-url', payload),
    createThumbnailUrl: (payload) => ipcRenderer.invoke('media:create-thumbnail-url', payload),
    resolveUrlToPath: (payload) => ipcRenderer.invoke('media:resolve-url-to-path', payload),
    getOriginalUrl: (payload) => ipcRenderer.invoke('media:get-original-url', payload),
  },
  auth: {
    login: (payload) => ipcRenderer.invoke('auth:login', payload),
    getCurrentUser: (payload) => ipcRenderer.invoke('auth:get-current-user', payload),
    updateLocalUser: (payload) => ipcRenderer.invoke('auth:update-local-user', payload),
    logout: () => ipcRenderer.invoke('auth:logout'),
    validateSession: (payload) => ipcRenderer.invoke('auth:validate-session', payload),
  },
  project: {
    getPageState: () => ipcRenderer.invoke('project:get-page-state'),
    create: (payload) => ipcRenderer.invoke('project:create', payload),
    update: (payload) => ipcRenderer.invoke('project:update', payload),
    getDeleteImpact: (payload) => ipcRenderer.invoke('project:delete-impact', payload),
    delete: (payload) => ipcRenderer.invoke('project:delete', payload),
    open: (payload) => ipcRenderer.invoke('project:open', payload),
    restoreRecent: () => ipcRenderer.invoke('project:recent:restore'),
    updateRecentRoute: (payload) => ipcRenderer.invoke('project:recent:update-route', payload),
    clearRecent: (payload) => ipcRenderer.invoke('project:recent:clear', payload),
    getFlowStats: (payload) => ipcRenderer.invoke('project:get-flow-stats', payload),
    exportPackage: (payload) => ipcRenderer.invoke('project:package:export', payload),
    importPackage: (payload) => ipcRenderer.invoke('project:package:import', payload),
    openPackageDirectory: (payload) => ipcRenderer.invoke('project:package:open-directory', payload),
    getManual: (payload) => ipcRenderer.invoke('project:manual:get', payload),
    saveManual: (payload) => ipcRenderer.invoke('project:manual:save', payload),
    deleteManual: (payload) => ipcRenderer.invoke('project:manual:delete', payload),
  },
  task: {
    list: (payload) => ipcRenderer.invoke('task:list', payload),
    categoryOptions: (payload) => ipcRenderer.invoke('task:category-options', payload),
    projectOptions: () => ipcRenderer.invoke('task:project-options'),
  },
  export: {
    buildTimeline: (payload) => ipcRenderer.invoke('export:timeline:build', payload),
    validateAssets: (payload) => ipcRenderer.invoke('export:assets:validate', payload),
    storyboardImages: (payload) => ipcRenderer.invoke('export:storyboard-images', payload),
    createJianyingDraft: (payload) => ipcRenderer.invoke('export:jianying:create-draft', payload),
    listHistory: (payload) => ipcRenderer.invoke('export:history:list', payload),
    getHistoryDetail: (payload) => ipcRenderer.invoke('export:history:detail', payload),
    openDirectory: (payload) => ipcRenderer.invoke('export:directory:open', payload),
  },
  source: {
    list: (payload) => ipcRenderer.invoke('source:list', payload),
    import: (payload) => ipcRenderer.invoke('source:import', payload),
    updateChapter: (payload) => ipcRenderer.invoke('source:update-chapter', payload),
    deleteChapter: (payload) => ipcRenderer.invoke('source:delete-chapter', payload),
    deleteChapters: (payload) => ipcRenderer.invoke('source:delete-chapters', payload),
    generateEvents: (payload) => ipcRenderer.invoke('source:generate-events', payload),
    pollEventStatus: (payload) => ipcRenderer.invoke('source:poll-event-status', payload),
  },
  script: {
    list: (payload) => ipcRenderer.invoke('script:list', payload),
    save: (payload) => ipcRenderer.invoke('script:save', payload),
    batchCreate: (payload) => ipcRenderer.invoke('script:batch-create', payload),
    delete: (payload) => ipcRenderer.invoke('script:delete', payload),
    batchDelete: (payload) => ipcRenderer.invoke('script:batch-delete', payload),
    exportZip: (payload) => ipcRenderer.invoke('script:export-zip', payload),
    generateParseRegex: (payload) => ipcRenderer.invoke('script:generate-parse-regex', payload),
    extractAssets: (payload) => ipcRenderer.invoke('script:extract-assets', payload),
    pollExtractStatus: (payload) => ipcRenderer.invoke('script:poll-extract-status', payload),
  },
  assets: {
    list: (payload) => ipcRenderer.invoke('assets:list', payload),
    save: (payload) => ipcRenderer.invoke('assets:save', payload),
    delete: (payload) => ipcRenderer.invoke('assets:delete', payload),
    batchDelete: (payload) => ipcRenderer.invoke('assets:batch-delete', payload),
    uploadMedia: (payload) => ipcRenderer.invoke('assets:upload-media', payload),
    generatePrompt: (payload) => ipcRenderer.invoke('assets:generate-prompt', payload),
    batchGeneratePrompts: (payload) => ipcRenderer.invoke('assets:batch-generate-prompts', payload),
    generateImage: (payload) => ipcRenderer.invoke('assets:generate-image', payload),
    batchGenerateImages: (payload) => ipcRenderer.invoke('assets:batch-generate-images', payload),
    selectMedia: (payload) => ipcRenderer.invoke('assets:select-media', payload),
    deleteMedia: (payload) => ipcRenderer.invoke('assets:delete-media', payload),
    cancelImage: (payload) => ipcRenderer.invoke('assets:cancel-image', payload),
    pollPromptStatus: (payload) => ipcRenderer.invoke('assets:poll-prompt-status', payload),
    pollImageStatus: (payload) => ipcRenderer.invoke('assets:poll-image-status', payload),
  },
  cornerScape: {
    list: (payload) => ipcRenderer.invoke('corner-scape:list', payload),
    updateAudioBinding: (payload) => ipcRenderer.invoke('corner-scape:update-audio-binding', payload),
    batchBindAudio: (payload) => ipcRenderer.invoke('corner-scape:batch-bind-audio', payload),
    pollAudioBindStatus: (payload) => ipcRenderer.invoke('corner-scape:poll-audio-bind-status', payload),
  },
  production: {
    getWorkspace: (payload) => ipcRenderer.invoke('production:workspace:get', payload),
    saveWorkspace: (payload) => ipcRenderer.invoke('production:workspace:save', payload),
    extractResources: (payload) => ipcRenderer.invoke('production:resources:extract', payload),
    agent: {
      getTools: () => ipcRenderer.invoke('production:agent:tools'),
      getContext: (payload) => ipcRenderer.invoke('production:agent:context', payload),
      applyWorkspacePatch: (payload) => ipcRenderer.invoke('production:agent:workspace-patch', payload),
      createStoryboard: (payload) => ipcRenderer.invoke('production:agent:storyboard:create', payload),
      createDerivedAsset: (payload) => ipcRenderer.invoke('production:agent:derived-asset:create', payload),
      deleteDerivedAsset: (payload) => ipcRenderer.invoke('production:agent:derived-asset:delete', payload),
      generateStoryboardImages: (payload) => ipcRenderer.invoke('production:agent:storyboard:generate-images', payload),
      generateDerivedAssetImages: (payload) => ipcRenderer.invoke('production:agent:derived-asset:generate-images', payload),
    },
    saveStoryboard: (payload) => ipcRenderer.invoke('production:storyboard:save', payload),
    deleteStoryboard: (payload) => ipcRenderer.invoke('production:storyboard:delete', payload),
    batchDeleteStoryboards: (payload) => ipcRenderer.invoke('production:storyboard:batch-delete', payload),
    generateStoryboardImages: (payload) => ipcRenderer.invoke('production:storyboard:generate-images', payload),
    pollStoryboardImages: (payload) => ipcRenderer.invoke('production:storyboard:poll-images', payload),
    saveDerivedAsset: (payload) => ipcRenderer.invoke('production:derived-asset:save', payload),
    deleteDerivedAsset: (payload) => ipcRenderer.invoke('production:derived-asset:delete', payload),
    generateDerivedAssetImages: (payload) => ipcRenderer.invoke('production:derived-asset:generate-images', payload),
    pollDerivedAssetImages: (payload) => ipcRenderer.invoke('production:derived-asset:poll-images', payload),
    getImageFlow: (payload) => ipcRenderer.invoke('production:image-flow:get', payload),
    saveImageFlow: (payload) => ipcRenderer.invoke('production:image-flow:save', payload),
    applyImageFlowResult: (payload) => ipcRenderer.invoke('production:image-flow:apply-result', payload),
    getWorkbench: (payload) => ipcRenderer.invoke('production:workbench:get', payload),
    saveVideoTrack: (payload) => ipcRenderer.invoke('production:video-track:save', payload),
    deleteVideoTrack: (payload) => ipcRenderer.invoke('production:video-track:delete', payload),
    generateVideoPrompts: (payload) => ipcRenderer.invoke('production:video-prompt:generate', payload),
    pollVideoPrompts: (payload) => ipcRenderer.invoke('production:video-prompt:poll', payload),
    generateVideos: (payload) => ipcRenderer.invoke('production:video:generate', payload),
    pollVideos: (payload) => ipcRenderer.invoke('production:video:poll', payload),
    selectVideo: (payload) => ipcRenderer.invoke('production:video:select', payload),
    deleteVideo: (payload) => ipcRenderer.invoke('production:video:delete', payload),
  },
  settings: {
    api: {
      list: () => ipcRenderer.invoke('settings:api:list'),
      templates: () => ipcRenderer.invoke('settings:api:templates'),
      save: (payload) => ipcRenderer.invoke('settings:api:save', payload),
      delete: (payload) => ipcRenderer.invoke('settings:api:delete', payload),
      test: (payload) => ipcRenderer.invoke('settings:api:test', payload),
    },
    modelTest: {
      openFileLocation: (payload) => ipcRenderer.invoke('settings:model-test:open-file-location', payload),
      saveFileAs: (payload) => ipcRenderer.invoke('settings:model-test:save-file-as', payload),
    },
    resource: {
      get: () => ipcRenderer.invoke('settings:resource:get'),
      saveBinding: (payload) => ipcRenderer.invoke('settings:resource:save-binding', payload),
      test: (payload) => ipcRenderer.invoke('settings:resource:test', payload),
    },
    agentConfig: {
      get: () => ipcRenderer.invoke('settings:agent-config:get'),
      save: (payload) => ipcRenderer.invoke('settings:agent-config:save', payload),
    },
    modelPrompt: {
      get: () => ipcRenderer.invoke('settings:model-prompt:get'),
      saveTemplate: (payload) => ipcRenderer.invoke('settings:model-prompt:save-template', payload),
      deleteTemplate: (payload) => ipcRenderer.invoke('settings:model-prompt:delete-template', payload),
      bind: (payload) => ipcRenderer.invoke('settings:model-prompt:bind', payload),
      clearBinding: (payload) => ipcRenderer.invoke('settings:model-prompt:clear-binding', payload),
    },
    prompt: {
      list: () => ipcRenderer.invoke('settings:prompt:list'),
      update: (payload) => ipcRenderer.invoke('settings:prompt:update', payload),
      restoreDefault: (payload) => ipcRenderer.invoke('settings:prompt:restore-default', payload),
    },
    memory: {
      get: () => ipcRenderer.invoke('settings:memory:get'),
      save: (payload) => ipcRenderer.invoke('settings:memory:save', payload),
      restoreDefault: () => ipcRenderer.invoke('settings:memory:restore-default'),
      validateModelPath: (payload) => ipcRenderer.invoke('settings:memory:validate-model-path', payload),
      clear: (payload) => ipcRenderer.invoke('settings:memory:clear', payload),
    },
    database: {
      info: () => ipcRenderer.invoke('settings:database:info'),
      listBackups: () => ipcRenderer.invoke('settings:database:list-backups'),
      export: () => ipcRenderer.invoke('settings:database:export'),
      import: (payload) => ipcRenderer.invoke('settings:database:import', payload),
      listTables: () => ipcRenderer.invoke('settings:database:list-tables'),
      clearTable: (payload) => ipcRenderer.invoke('settings:database:clear-table', payload),
      clearAll: (payload) => ipcRenderer.invoke('settings:database:clear-all', payload),
      checkRunningTasks: () => ipcRenderer.invoke('settings:database:check-running-tasks'),
    },
    files: {
      listOpenableDirs: () => ipcRenderer.invoke('settings:files:list-openable-dirs'),
      openDir: (payload) => ipcRenderer.invoke('settings:files:open-dir', payload),
      diagnoseLifecycle: () => ipcRenderer.invoke('settings:files:diagnose-lifecycle'),
      cleanupLifecycle: (payload) => ipcRenderer.invoke('settings:files:cleanup-lifecycle', payload),
    },
    business: {
      get: () => ipcRenderer.invoke('settings:business:get'),
      save: (payload) => ipcRenderer.invoke('settings:business:save', payload),
      restoreDefaultChapterReg: () => ipcRenderer.invoke('settings:business:restore-default-chapter-reg'),
    },
    request: {
      get: () => ipcRenderer.invoke('settings:request:get'),
      refreshLocalUrl: () => ipcRenderer.invoke('settings:request:refresh-local-url'),
    },
    dev: {
      get: () => ipcRenderer.invoke('settings:dev:get'),
      save: (payload) => ipcRenderer.invoke('settings:dev:save', payload),
      openDevTools: () => ipcRenderer.invoke('settings:dev:open-devtools'),
    },
    about: {
      get: () => ipcRenderer.invoke('settings:about:get'),
      checkUpdate: (payload) => ipcRenderer.invoke('settings:about:check-update', payload),
      download: (payload) => ipcRenderer.invoke('settings:about:download', payload),
      openLink: (payload) => ipcRenderer.invoke('settings:about:open-link', payload),
    },
    skill: {
      list: (payload) => ipcRenderer.invoke('settings:skill:list', payload),
      getContent: (payload) => ipcRenderer.invoke('settings:skill:get-content', payload),
      saveContent: (payload) => ipcRenderer.invoke('settings:skill:save-content', payload),
      rebuildEmbeddings: (payload) => ipcRenderer.invoke('settings:skill:rebuild-embeddings', payload),
    },
    vendor: {
      list: () => ipcRenderer.invoke('settings:vendor:list'),
      updateInputs: (payload) => ipcRenderer.invoke('settings:vendor:update-inputs', payload),
      setEnabled: (payload) => ipcRenderer.invoke('settings:vendor:set-enabled', payload),
      saveModel: (payload) => ipcRenderer.invoke('settings:vendor:save-model', payload),
      deleteModel: (payload) => ipcRenderer.invoke('settings:vendor:delete-model', payload),
      getCode: (payload) => ipcRenderer.invoke('settings:vendor:get-code', payload),
      addCode: (payload) => ipcRenderer.invoke('settings:vendor:add-code', payload),
      updateCode: (payload) => ipcRenderer.invoke('settings:vendor:update-code', payload),
      delete: (payload) => ipcRenderer.invoke('settings:vendor:delete', payload),
      testText: (payload) => ipcRenderer.invoke('settings:vendor:test-text', payload),
      testImage: (payload) => ipcRenderer.invoke('settings:vendor:test-image', payload),
      testVideo: (payload) => ipcRenderer.invoke('settings:vendor:test-video', payload),
    },
  },
};

contextBridge.exposeInMainWorld('vtStudio', api);
