export const VT_STATUS = {
  OK: 200,
  TASK_ACCEPTED: 202,
  FAIL: 400,
  INVALID_PARAMS: 40001,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  SYSTEM_ERROR: 500,
  FILE_ERROR: 60000,
  FILE_PATH_INVALID: 60001,
  FILE_PATH_ESCAPE: 60002,
  FILE_NOT_FOUND: 60003,
  FILE_ALREADY_EXISTS: 60004,
  FILE_READ_FAILED: 60005,
  FILE_WRITE_FAILED: 60006,
  FILE_DELETE_FAILED: 60007,
  DIRECTORY_CREATE_FAILED: 60008,
  DIRECTORY_NOT_EMPTY: 60009,
  UNSUPPORTED_FILE_TYPE: 60010,
  DATABASE_ERROR: 61000,
  DATABASE_MIGRATION_ERROR: 61001,
  DATABASE_TRANSACTION_ERROR: 61002,
  MODEL_ERROR: 70000,
  MODEL_NOT_CONFIGURED: 70001,
  MODEL_API_KEY_MISSING: 70002,
  MODEL_VENDOR_NOT_FOUND: 70003,
  MODEL_VENDOR_INVALID: 70004,
  MODEL_NOT_FOUND: 70005,
  MODEL_VENDOR_INPUT_MISSING: 70006,
  MODEL_TIMEOUT: 70007,
  EMBEDDING_ERROR: 71000,
  EMBEDDING_MODEL_NOT_FOUND: 71001,
  EMBEDDING_MODEL_INVALID: 71002,
  TASK_ERROR: 80000,
  TASK_NOT_FOUND: 80001,
  TASK_CANCELLED: 80002,
  TASK_STATUS_CONFLICT: 80003,
  AGENT_ERROR: 90000,
  AGENT_SESSION_NOT_FOUND: 90001,
  MEMORY_ERROR: 92000,
  SKILL_ERROR: 93000,
  EXPORT_ERROR: 100000,
  EXPORT_MATERIAL_MISSING: 100001,
} as const;

export type VtStatusCode = (typeof VT_STATUS)[keyof typeof VT_STATUS];

export type VtLocale = 'zh-CN' | 'en';

export const DEFAULT_LOCALE: VtLocale = 'zh-CN';

const statusMessages: Record<VtLocale, Partial<Record<VtStatusCode, string>>> = {
  'zh-CN': {
    [VT_STATUS.OK]: '成功',
    [VT_STATUS.TASK_ACCEPTED]: '任务已创建',
    [VT_STATUS.FAIL]: '请求失败',
    [VT_STATUS.INVALID_PARAMS]: '参数错误',
    [VT_STATUS.UNAUTHORIZED]: '登录已失效',
    [VT_STATUS.FORBIDDEN]: '没有操作权限',
    [VT_STATUS.NOT_FOUND]: '数据不存在',
    [VT_STATUS.CONFLICT]: '当前状态不允许操作',
    [VT_STATUS.SYSTEM_ERROR]: '系统异常',
    [VT_STATUS.FILE_ERROR]: '文件处理失败',
    [VT_STATUS.FILE_PATH_INVALID]: '文件路径无效',
    [VT_STATUS.FILE_PATH_ESCAPE]: '文件路径越界',
    [VT_STATUS.FILE_NOT_FOUND]: '文件不存在',
    [VT_STATUS.FILE_ALREADY_EXISTS]: '文件已存在',
    [VT_STATUS.FILE_READ_FAILED]: '文件读取失败',
    [VT_STATUS.FILE_WRITE_FAILED]: '文件写入失败',
    [VT_STATUS.FILE_DELETE_FAILED]: '文件删除失败',
    [VT_STATUS.DIRECTORY_CREATE_FAILED]: '目录创建失败',
    [VT_STATUS.DIRECTORY_NOT_EMPTY]: '目录非空',
    [VT_STATUS.UNSUPPORTED_FILE_TYPE]: '不支持的文件类型',
    [VT_STATUS.DATABASE_ERROR]: '数据库处理失败',
    [VT_STATUS.DATABASE_MIGRATION_ERROR]: '数据库迁移失败',
    [VT_STATUS.DATABASE_TRANSACTION_ERROR]: '数据库事务失败',
    [VT_STATUS.MODEL_ERROR]: '模型调用失败',
    [VT_STATUS.MODEL_NOT_CONFIGURED]: '模型未配置',
    [VT_STATUS.MODEL_API_KEY_MISSING]: 'API Key 缺失',
    [VT_STATUS.MODEL_VENDOR_NOT_FOUND]: '供应商不存在',
    [VT_STATUS.MODEL_VENDOR_INVALID]: '供应商配置无效',
    [VT_STATUS.MODEL_NOT_FOUND]: '模型不存在',
    [VT_STATUS.MODEL_VENDOR_INPUT_MISSING]: '供应商参数缺失',
    [VT_STATUS.MODEL_TIMEOUT]: '模型调用超时',
    [VT_STATUS.EMBEDDING_ERROR]: '向量模型处理失败',
    [VT_STATUS.EMBEDDING_MODEL_NOT_FOUND]: '本地向量模型不存在',
    [VT_STATUS.EMBEDDING_MODEL_INVALID]: '本地向量模型配置无效',
    [VT_STATUS.TASK_ERROR]: '任务处理失败',
    [VT_STATUS.TASK_NOT_FOUND]: '任务不存在',
    [VT_STATUS.TASK_CANCELLED]: '任务已取消',
    [VT_STATUS.TASK_STATUS_CONFLICT]: '任务状态不允许当前操作',
    [VT_STATUS.AGENT_ERROR]: 'Agent 处理失败',
    [VT_STATUS.AGENT_SESSION_NOT_FOUND]: 'Agent 会话不存在',
    [VT_STATUS.MEMORY_ERROR]: '记忆处理失败',
    [VT_STATUS.SKILL_ERROR]: 'Skill 处理失败',
    [VT_STATUS.EXPORT_ERROR]: '导出失败',
    [VT_STATUS.EXPORT_MATERIAL_MISSING]: '导出素材缺失',
  },
  en: {
    [VT_STATUS.OK]: 'Success',
    [VT_STATUS.TASK_ACCEPTED]: 'Task created',
    [VT_STATUS.FAIL]: 'Request failed',
    [VT_STATUS.INVALID_PARAMS]: 'Invalid parameters',
    [VT_STATUS.UNAUTHORIZED]: 'Session expired',
    [VT_STATUS.FORBIDDEN]: 'Permission denied',
    [VT_STATUS.NOT_FOUND]: 'Data not found',
    [VT_STATUS.CONFLICT]: 'Current state does not allow this operation',
    [VT_STATUS.SYSTEM_ERROR]: 'System error',
    [VT_STATUS.FILE_ERROR]: 'File operation failed',
    [VT_STATUS.FILE_PATH_INVALID]: 'Invalid file path',
    [VT_STATUS.FILE_PATH_ESCAPE]: 'File path escapes the allowed directory',
    [VT_STATUS.FILE_NOT_FOUND]: 'File not found',
    [VT_STATUS.FILE_ALREADY_EXISTS]: 'File already exists',
    [VT_STATUS.FILE_READ_FAILED]: 'File read failed',
    [VT_STATUS.FILE_WRITE_FAILED]: 'File write failed',
    [VT_STATUS.FILE_DELETE_FAILED]: 'File delete failed',
    [VT_STATUS.DIRECTORY_CREATE_FAILED]: 'Directory creation failed',
    [VT_STATUS.DIRECTORY_NOT_EMPTY]: 'Directory is not empty',
    [VT_STATUS.UNSUPPORTED_FILE_TYPE]: 'Unsupported file type',
    [VT_STATUS.DATABASE_ERROR]: 'Database operation failed',
    [VT_STATUS.DATABASE_MIGRATION_ERROR]: 'Database migration failed',
    [VT_STATUS.DATABASE_TRANSACTION_ERROR]: 'Database transaction failed',
    [VT_STATUS.MODEL_ERROR]: 'Model call failed',
    [VT_STATUS.MODEL_NOT_CONFIGURED]: 'Model is not configured',
    [VT_STATUS.MODEL_API_KEY_MISSING]: 'API key is missing',
    [VT_STATUS.MODEL_VENDOR_NOT_FOUND]: 'Model vendor not found',
    [VT_STATUS.MODEL_VENDOR_INVALID]: 'Invalid model vendor config',
    [VT_STATUS.MODEL_NOT_FOUND]: 'Model not found',
    [VT_STATUS.MODEL_VENDOR_INPUT_MISSING]: 'Model vendor input is missing',
    [VT_STATUS.MODEL_TIMEOUT]: 'Model call timed out',
    [VT_STATUS.EMBEDDING_ERROR]: 'Embedding model failed',
    [VT_STATUS.EMBEDDING_MODEL_NOT_FOUND]: 'Local embedding model not found',
    [VT_STATUS.EMBEDDING_MODEL_INVALID]: 'Invalid local embedding model config',
    [VT_STATUS.TASK_ERROR]: 'Task failed',
    [VT_STATUS.TASK_NOT_FOUND]: 'Task not found',
    [VT_STATUS.TASK_CANCELLED]: 'Task cancelled',
    [VT_STATUS.TASK_STATUS_CONFLICT]: 'Task status does not allow this operation',
    [VT_STATUS.AGENT_ERROR]: 'Agent failed',
    [VT_STATUS.AGENT_SESSION_NOT_FOUND]: 'Agent session not found',
    [VT_STATUS.MEMORY_ERROR]: 'Memory operation failed',
    [VT_STATUS.SKILL_ERROR]: 'Skill operation failed',
    [VT_STATUS.EXPORT_ERROR]: 'Export failed',
    [VT_STATUS.EXPORT_MATERIAL_MISSING]: 'Export material is missing',
  },
};

export function getStatusMsg(code: VtStatusCode, locale: VtLocale = DEFAULT_LOCALE): string {
  return statusMessages[locale][code] ?? statusMessages[DEFAULT_LOCALE][code] ?? statusMessages[DEFAULT_LOCALE][VT_STATUS.FAIL]!;
}

export function getStatusMsgKey(code: VtStatusCode): string {
  return `status.${code}`;
}
